create table if not exists "server_plugin_packages" ("tenant_id" text not null, "plugin_id" text not null, "manifest_json" text not null, "document_json" text not null, "config_json" text default '{}' not null, "enabled" integer default 1 not null check (enabled in (0, 1)), "created_at" integer not null, "updated_at" integer not null, constraint "pk_server_plugin_packages" primary key ("tenant_id", "plugin_id"));

create table if not exists "server_plugin_schedules" ("tenant_id" text not null, "plugin_id" text not null, "flow_id" text not null, "enabled" integer default 0 not null check (enabled in (0, 1)), "interval_hours" integer not null check (interval_hours between 1 and 168), "next_run_at" integer not null, "updated_at" integer not null, constraint "pk_server_plugin_schedules" primary key ("tenant_id", "plugin_id"), constraint "fk_server_plugin_schedules_tenant_id_plugin_id" foreign key ("tenant_id", "plugin_id") references "server_plugin_packages" ("tenant_id", "plugin_id") on delete cascade);
create index if not exists "idx_server_plugin_schedules_due" on "server_plugin_schedules" ("enabled", "next_run_at");

create table if not exists "server_plugin_runs" ("id" text not null primary key, "tenant_id" text not null, "plugin_id" text not null, "flow_id" text not null, "trigger" text not null check (trigger in ('manual', 'scheduled')), "status" text not null check (status in ('running', 'succeeded', 'failed')), "input_json" text, "result_json" text, "step_id" text, "error_message" text, "metrics_json" text not null, "started_at" integer not null, "completed_at" integer);
create index if not exists "idx_server_plugin_runs_tenant_plugin_started" on "server_plugin_runs" ("tenant_id", "plugin_id", "started_at" desc);

create table if not exists "server_plugin_store" ("tenant_id" text not null, "plugin_id" text not null, "key" text not null, "value_json" text not null, constraint "pk_server_plugin_store" primary key ("tenant_id", "plugin_id", "key"), constraint "fk_server_plugin_store_tenant_id_plugin_id" foreign key ("tenant_id", "plugin_id") references "server_plugin_packages" ("tenant_id", "plugin_id") on delete cascade);
