// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult } from 'taurpc'
export type Error = string;

export type FrontendLogEntry = {
	timestamp: string,
	scope: string,
	level: LogLevel,
	content: string,
};

export type LogFileContent = {
	path: string,
	content: string,
	/**  Uncompressed byte size. */
	size: number,
	truncated: boolean,
};

export type LogFileInfo = {
	/**  Safe relative path accepted by `read_log_file` and `export_logs`. */
	path: string,
	name: string,
	size: number,
	modifiedAt: string,
	archived: boolean,
};

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

export type Result<T, E> = {
	ok: T,
	err: E,
};
const ARGS_MAP = {"logger":{"export_logs":["paths"],"list_log_files":[],"read_log_file":["path"],"write_logs":["entries"]}};

const RESULT_MAP = {"logger":{"export_logs":true,"list_log_files":true,"read_log_file":true,"write_logs":true}};

export type Router = {
	logger: {
		export_logs: (paths: string[] | null) => Promise<string>,
		list_log_files: () => Promise<LogFileInfo[]>,
		read_log_file: (path: string) => Promise<LogFileContent>,
		write_logs: (entries: FrontendLogEntry[]) => Promise<null>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }
