/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./lib/components/user/actionCard.vue')['default']
    CreateFavouriteCard: typeof import('./lib/components/createFavouriteCard.vue')['default']
    DestinationSelect: typeof import('./lib/components/download/DestinationSelect.vue')['default']
    DownloadTaskActions: typeof import('./lib/components/download/DownloadTaskActions.vue')['default']
    DownloadTaskInfo: typeof import('./lib/components/download/DownloadTaskInfo.vue')['default']
    FavouriteCard: typeof import('./lib/components/user/favouriteCard.vue')['default']
    FavouriteFolderList: typeof import('./lib/components/user/favourite/FavouriteFolderList.vue')['default']
    FavouriteItem: typeof import('./lib/components/user/favouriteItem.vue')['default']
    FavouriteSelect: typeof import('./lib/components/favouriteSelect.vue')['default']
    ForkSelect: typeof import('./lib/components/forkSelect.vue')['default']
    HistoryCard: typeof import('./lib/components/user/historyCard.vue')['default']
    HotMainListBlock: typeof import('./lib/components/home/HotMainListBlock.vue')['default']
    HotSearchPanel: typeof import('./lib/components/search/landing/HotSearchPanel.vue')['default']
    ListAction: typeof import('./lib/components/listAction.vue')['default']
    ListSearcher: typeof import('./lib/components/listSearcher.vue')['default']
    LogText: typeof import('./lib/components/logs/LogText.vue')['default']
    MainPageSearchBar: typeof import('./lib/components/home/mainPageSearchBar.vue')['default']
    PluginConfigField: typeof import('./lib/components/plugin/PluginConfigField.vue')['default']
    PluginIcon: typeof import('./lib/components/plugin/PluginIcon.vue')['default']
    PluginMarketplaceCard: typeof import('./lib/components/plugin/marketplace/PluginMarketplaceCard.vue')['default']
    PluginMarketplaceContainer: typeof import('./lib/components/plugin/marketplace/PluginMarketplaceContainer.vue')['default']
    PluginMarketplaceDetails: typeof import('./lib/components/plugin/marketplace/PluginMarketplaceDetails.vue')['default']
    PluginMarketplaceFilters: typeof import('./lib/components/plugin/marketplace/PluginMarketplaceFilters.vue')['default']
    PluginMarketplaceList: typeof import('./lib/components/plugin/marketplace/PluginMarketplaceList.vue')['default']
    RecentCard: typeof import('./lib/components/user/recentCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHistoryPanel: typeof import('./lib/components/search/landing/SearchHistoryPanel.vue')['default']
    SearchLandingForm: typeof import('./lib/components/search/landing/SearchLandingForm.vue')['default']
    SubAuthorList: typeof import('./lib/components/subscribe/subAuthorList.vue')['default']
    SubCard: typeof import('./lib/components/subscribe/subCard.vue')['default']
    SubList: typeof import('./lib/components/subscribe/subList.vue')['default']
    UserFavouriteSelect: typeof import('./lib/components/user/userFavouriteSelect.vue')['default']
  }
}
