[workspace]
resolver = "3"
members = [
  "packages/app/src-tauri",
  "packages/db",
  "packages/downloader",
  "packages/downloader/tools/performance-baseline",
  "packages/logger",
  "packages/plugin",
  "packages/utils",
]

[workspace.package]
authors = ["wenxig"]
edition = "2024"
license = "AGPL-3.0-only"
repository = "https://github.com/delta-comic/delta-comic"
rust-version = "1.95.0"
version = "3.0.0-next.16"

[workspace.dependencies]
log = "0.4.33"
mime_guess = "2.0.5"
objc2-foundation = { version = "0.3.2", features = ["NSString", "NSUserDefaults"] }
percent-encoding = "2.3.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = "2.11.5"
tauri-build = "2.6.3"
tauri-plugin = "2.6.3"
tauri-plugin-aptabase = { git = "https://github.com/delta-comic/tauri-plugin-aptabase-rustls", branch = "main" }
tauri-plugin-better-cors-fetch = { version = "1.8.0", features = ["multipart", "blocking"] }
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-db = { path = "packages/db" }
tauri-plugin-downloader = { path = "packages/downloader" }
tauri-plugin-logger = { path = "packages/logger" }
tauri-plugin-fs = "2.5.1"
tauri-plugin-m3 = "0.3.1"
tauri-plugin-persisted-scope = "2.3.7"
tauri-plugin-plugin = { path = "packages/plugin" }
tauri-plugin-shell = "2"
tauri-plugin-webview-upgrade = { git = "https://github.com/readest/tauri-plugin-webview-upgrade" }

tauri-plugin-sql = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2", features = [
  "sqlite",
] }
tauri-plugin-utils = { path = "packages/utils" }
tauri-runtime-wry = "2.11.4"
tokio = "1.53.1"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
zip = { version = "8.6.0", default-features = false, features = ["deflate-flate2"] }

[profile.dev]
debug = "line-tables-only"
overflow-checks = true
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true
debug = false
incremental = false