// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	fetch: (contentConfig: ContentConfig) => __TAURI_INVOKE<number>("plugin:http|fetch", { contentConfig }),
	fetchCancel: (rid: number) => __TAURI_INVOKE<null>("plugin:http|fetch_cancel", { rid }),
	fetchSend: (rid: number) => __TAURI_INVOKE<FetchResponse>("plugin:http|fetch_send", { rid }),
	fetchCancelBody: (rid: number) => __TAURI_INVOKE<null>("plugin:http|fetch_cancel_body", { rid }),
	prepareRequester: (client: ClientConfig) => __TAURI_INVOKE<void>("plugin:http|prepare_requester", { client }),
	setCookie: (config: SetCookieConfig) => __TAURI_INVOKE<null>("plugin:http|set_cookie", { config }),
	getCookie: (config: GetCookieConfig) => __TAURI_INVOKE<string | null>("plugin:http|get_cookie", { config }),
	getAllCookies: (config: GetAllCookiesConfig) => __TAURI_INVOKE<CookieEntry[]>("plugin:http|get_all_cookies", { config }),
	getAllDomainCookies: (config: GetAllDomainCookiesConfig) => __TAURI_INVOKE<CookieEntry[]>("plugin:http|get_all_domain_cookies", { config }),
	deleteCookie: (config: DeleteCookieConfig) => __TAURI_INVOKE<boolean>("plugin:http|delete_cookie", { config }),
	clearCookie: (config: ClearCookiesConfig) => __TAURI_INVOKE<null>("plugin:http|clear_cookie", { config }),
};

/* Types */
export type BasicAuth = {
	username: string,
	password: string,
};

export type ClearCookiesConfig = {
	instanceKey: string,
};

export type ClientConfig = {
	connectTimeout: number | null,
	maxRedirections: number | null,
	proxy: Proxy | null,
	danger: DangerousSettings | null,
	userAgent: string | null,
	instanceKey: string,
};

export type ContentConfig = {
	method: string,
	url: string,
	headers: ([string, string])[],
	data: number[] | null,
	client: ClientConfig,
};

export type CookieEntry = {
	domain: string,
	name: string,
	value: string,
};

export type DangerousSettings = {
	acceptInvalidCerts: boolean,
	acceptInvalidHostnames: boolean,
};

export type DeleteCookieConfig = {
	url: string,
	path: string | null,
	name: string,
	instanceKey: string,
};

export type Error = string;

export type FetchResponse = {
	status: number,
	statusText: string,
	headers: ([string, string])[],
	url: string,
	rid: number,
};

export type GetAllCookiesConfig = {
	instanceKey: string,
};

export type GetAllDomainCookiesConfig = {
	url: string,
	instanceKey: string,
};

export type GetCookieConfig = {
	url: string,
	name: string,
	instanceKey: string,
};

export type Proxy = {
	all: UrlOrConfig | null,
	http: UrlOrConfig | null,
	https: UrlOrConfig | null,
};

export type ProxyConfig = {
	url: string,
	basicAuth: BasicAuth | null,
	noProxy: string | null,
};

export type SetCookieConfig = {
	url: string,
	content: string,
	instanceKey: string,
};

export type UrlOrConfig = string | ProxyConfig;
