// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult } from 'taurpc'
export type AuthCallbackSnapshot = {
	value?: unknown,
	href?: string,
	title?: string,
	cookie?: string,
	localStorage?: StorageEntry[],
	sessionStorage?: StorageEntry[],
	collectedAt?: number,
};

export type InaccessibleFrame = {
	index: number,
	src?: string,
	error: string,
};

export type InjectCodeOptions = {
	label: string | null,
	css: string | null,
	js: string | null,
	callbackName: string | null,
};

export type OpenPageOptions = {
	url: string,
	label: string | null,
	title: string | null,
	css: string | null,
	js: string | null,
	callbackName: string | null,
	allFrames: boolean | null,
	visible: boolean | null,
	width: number | null,
	height: number | null,
	userAgent: string | null,
	incognito: boolean | null,
	devtools: boolean | null,
};

export type OpenedPage = {
	label: string,
	url: string,
};

export type Result<T, E> = {
	ok: T,
	err: E,
};

export type StorageEntry = {
	key: string,
	value: string,
};

export type WebStorageSnapshot = {
	frameId?: string,
	reason?: string,
	top?: boolean,
	href?: string,
	origin?: string,
	title?: string,
	cookie?: string,
	localStorage?: StorageEntry[],
	sessionStorage?: StorageEntry[],
	callback?: AuthCallbackSnapshot | null,
	errors?: string[],
	collectedAt?: number,
};

export type WebviewAuthData = {
	label: string,
	url: string,
	cookies?: WebviewCookie[],
	storage?: WebStorageSnapshot,
	frames?: WebStorageSnapshot[],
	inaccessibleFrames?: InaccessibleFrame[],
};

export type WebviewCookie = {
	name: string,
	value: string,
	domain?: string | null,
	path?: string | null,
	secure?: boolean | null,
	httpOnly?: boolean | null,
	sameSite?: string | null,
	expires?: string | null,
	source?: string,
};
const ARGS_MAP = {"utils":{"webview_auth_data":["label"],"webview_auth_data_all":[],"webview_auth_data_current":[],"webview_close_current_page":[],"webview_close_page":["label"],"webview_iframe_auth_data":["label","wait_ms"],"webview_inject_code":["options"],"webview_open_page":["options"]}};

const RESULT_MAP = {"utils":{"webview_auth_data":true,"webview_auth_data_all":true,"webview_auth_data_current":true,"webview_close_current_page":true,"webview_close_page":true,"webview_iframe_auth_data":true,"webview_inject_code":true,"webview_open_page":true}};

export type Router = {
	utils: {
		webview_auth_data: (label: string) => Promise<WebviewAuthData>,
		webview_auth_data_all: () => Promise<WebviewAuthData[]>,
		webview_auth_data_current: () => Promise<WebviewAuthData>,
		webview_close_current_page: () => Promise<null>,
		webview_close_page: (label: string) => Promise<null>,
		webview_iframe_auth_data: (label: string, waitMs: number | null) => Promise<WebviewAuthData>,
		webview_inject_code: (options: InjectCodeOptions) => Promise<null>,
		webview_open_page: (options: OpenPageOptions) => Promise<OpenedPage>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }
