// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult, type UnlistenFn } from 'taurpc'
export type InstallProgress = {
	current: number,
	opId: string,
	path: string | null,
	phase: string,
	total: number,
};

export type LocalFile = {
	bytes: number[],
	name: string,
};

export type Result<T, E> = {
	ok: T,
	err: E,
};
const ARGS_MAP = {"plugin":{"decode_zip_meta":["zip_path"],"install_progress":["event"],"install_zip":["zip_path","op_id"],"read_local_file":["path"]}};

const RESULT_MAP = {"plugin":{"decode_zip_meta":true,"install_progress":false,"install_zip":true,"read_local_file":true}};

export type Router = {
	plugin: {
		decode_zip_meta: (zipPath: string) => Promise<string>,
		install_progress: { on: (listener: (event: InstallProgress) => void) => Promise<UnlistenFn> },
		install_zip: (zipPath: string, opId: string) => Promise<string>,
		read_local_file: (path: string) => Promise<LocalFile>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }
