// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult, type UnlistenFn } from 'taurpc'
export type AttentionEvent = {
	taskId: string,
	code: string,
	message: string,
	revision: number,
};

export type ByteRange = {
	start: number,
	end: number,
};

export type Checksum = {
	algorithm: ChecksumAlgorithm,
	value: string,
};

export type ChecksumAlgorithm = "sha256" | "md5";

export type ContentRefreshContext = {
	plugin: string,
	contentType: [string, string],
	contentId: string,
	episodeId: string,
	contentPageFingerprint: string | null,
	providerFingerprint: string,
	pluginVersion: string | null,
	pluginIntegrity: string | null,
};

export type Destination = Destination_Serialize | Destination_Deserialize;

export type DestinationKind = "managed" | "desktopDirectory" | "androidSaf";

export type Destination_Deserialize = {
	id: string,
	label: string,
	kind: DestinationKind,
	path: string,
	isDefault: boolean,
};

export type Destination_Serialize = {
	id: string,
	label: string,
	kind: DestinationKind,
	isDefault: boolean,
};

export type DownloadAsset = {
	key: string,
	relativePath: string,
	size: number | null,
	checksum: Checksum | null,
	source: DownloadSource,
};

export type DownloadCollection = {
	key: string,
	title: string,
	destinationId: string,
	refreshContext: ContentRefreshContext | null,
	taskCount: number,
	completedTasks: number,
	totalBytes: number | null,
	downloadedBytes: number,
	createdAt: number,
};

export type DownloadSource = {
	type: "http",
} & HttpSource | {
	type: "torrent",
} & TorrentSource;

export type DownloadTask = {
	id: string,
	collectionKey: string | null,
	assetKey: string | null,
	kind: TaskKind,
	title: string,
	source: DownloadSource,
	destinationId: string,
	relativePath: string,
	status: TaskStatus,
	priority: number,
	queuePosition: number,
	totalBytes: number | null,
	downloadedBytes: number,
	speedBytesPerSecond: number,
	errorCode: string | null,
	errorMessage: string | null,
	checksum: Checksum | null,
	etag: string | null,
	lastModified: string | null,
	finalPath: string | null,
	retryCount: number,
	createdAt: number,
	updatedAt: number,
	revision: number,
};

export type DownloadTaskDetail = {
	task: DownloadTask,
	completedRanges: ByteRange[],
	torrent: TorrentTaskDetail | null,
};

export type DownloaderCapabilities = {
	connectionBudgetMax: number,
	maxActiveTasks: number,
};

export type DownloaderSettings = {
	maxActiveTasks: number,
	connectionBudget: number,
	perTaskConnections: number,
	allowMetered: boolean,
	seedOnComplete: boolean,
	seedRatio: number | null,
	seedSeconds: number | null,
	revision: number,
};

export type EnqueuePlanInput = {
	key: string,
	title: string,
	assets: DownloadAsset[],
	destinationId: string | null,
	priority: number | null,
	refreshContext: ContentRefreshContext | null,
};

export type EnqueueTorrentInput = {
	source: TorrentSource,
	title: string | null,
	relativePath: string | null,
	destinationId: string | null,
	priority: number | null,
};

export type EnqueueUrlInput = {
	url: string,
	title: string | null,
	relativePath: string | null,
	destinationId: string | null,
	priority: number | null,
	checksum: Checksum | null,
	mirrors?: HttpMirror[],
};

export type HttpHeaderValue = { type: "value"; value: string } | { type: "secretRef"; secret_ref: string };

export type HttpMirror = {
	url: string,
	priority?: number,
	headers?: { [key in string]: HttpHeaderValue },
};

export type HttpSource = {
	mirrors: HttpMirror[],
	expectedSize: number | null,
	etag: string | null,
	lastModified: string | null,
	expiresAt: number | null,
};

export type Result<T, E> = {
	ok: T,
	err: E,
};

export type SeedPolicy = { mode: "none" } | { mode: "ratio"; ratio: number | null } | { mode: "duration"; duration_seconds: number } | { mode: "ratioOrDuration"; ratio: number | null; duration_seconds: number };

export type TaskKind = "http" | "torrent";

export type TaskRemovedEvent = {
	taskId: string,
	revision: number,
};

export type TaskStatus = "queued" | "probing" | "downloading" | "waitingForNetwork" | "waitingForSource" | "paused" | "verifying" | "seeding" | "completed" | "failed" | "cancelled";

export type TaskUpsertEvent = {
	task: DownloadTask,
	revision: number,
};

export type TorrentInput = { type: "magnet"; uri: string } | { type: "url"; url: string } | { type: "bytes"; base64: string };

export type TorrentSource = {
	input: TorrentInput,
	onlyFiles?: number[],
	seedPolicy: SeedPolicy | null,
};

export type TorrentTaskDetail = {
	infoHash: string | null,
	uploadedBytes: number,
	peerCount: number,
	seedStartedAt: number | null,
};
const ARGS_MAP = {"downloader":{"attention":["event"],"cancel_task":["id"],"delete_secret":["secret_ref"],"delete_task_files":["id"],"download_ephemeral":["url","headers","secret_ref","max_bytes"],"enqueue_plan":["input"],"enqueue_torrent":["input"],"enqueue_url":["input"],"forget_task":["id"],"get_capabilities":[],"get_collections":[],"get_settings":[],"get_task":["id"],"get_task_detail":["id"],"list_destinations":[],"list_tasks":[],"move_queue":["id","before_task_id"],"pause_task":["id"],"pick_destination":[],"resume_task":["id"],"retry_task":["id"],"set_priority":["id","priority"],"store_secret":["value"],"task_removed":["event"],"task_upsert":["event"],"update_settings":["settings"],"update_source":["id","source"]}};

const RESULT_MAP = {"downloader":{"attention":false,"cancel_task":true,"delete_secret":true,"delete_task_files":true,"download_ephemeral":true,"enqueue_plan":true,"enqueue_torrent":true,"enqueue_url":true,"forget_task":true,"get_capabilities":true,"get_collections":true,"get_settings":true,"get_task":true,"get_task_detail":true,"list_destinations":true,"list_tasks":true,"move_queue":true,"pause_task":true,"pick_destination":true,"resume_task":true,"retry_task":true,"set_priority":true,"store_secret":true,"task_removed":false,"task_upsert":false,"update_settings":true,"update_source":true}};

export type Router = {
	downloader: {
		attention: { on: (listener: (event: AttentionEvent) => void) => Promise<UnlistenFn> },
		cancel_task: (id: string) => Promise<DownloadTask>,
		delete_secret: (secretRef: string) => Promise<null>,
		delete_task_files: (id: string) => Promise<null>,
		download_ephemeral: (url: string, headers: { [key in string]: string } | null, secretRef: string | null, maxBytes: number | null) => Promise<number[]>,
		enqueue_plan: (input: EnqueuePlanInput) => Promise<DownloadTask[]>,
		enqueue_torrent: (input: EnqueueTorrentInput) => Promise<DownloadTask>,
		enqueue_url: (input: EnqueueUrlInput) => Promise<DownloadTask>,
		forget_task: (id: string) => Promise<null>,
		get_capabilities: () => Promise<DownloaderCapabilities>,
		get_collections: () => Promise<DownloadCollection[]>,
		get_settings: () => Promise<DownloaderSettings>,
		get_task: (id: string) => Promise<{
	id: string,
	collectionKey: string | null,
	assetKey: string | null,
	kind: TaskKind,
	title: string,
	source: DownloadSource,
	destinationId: string,
	relativePath: string,
	status: TaskStatus,
	priority: number,
	queuePosition: number,
	totalBytes: number | null,
	downloadedBytes: number,
	speedBytesPerSecond: number,
	errorCode: string | null,
	errorMessage: string | null,
	checksum: Checksum | null,
	etag: string | null,
	lastModified: string | null,
	finalPath: string | null,
	retryCount: number,
	createdAt: number,
	updatedAt: number,
	revision: number,
} | null>,
		get_task_detail: (id: string) => Promise<DownloadTaskDetail>,
		list_destinations: () => Promise<Destination_Serialize[]>,
		list_tasks: () => Promise<DownloadTask[]>,
		move_queue: (id: string, beforeTaskId: string | null) => Promise<DownloadTask>,
		pause_task: (id: string) => Promise<DownloadTask>,
		pick_destination: () => Promise<{
	id: string,
	label: string,
	kind: DestinationKind,
	isDefault: boolean,
} | null>,
		resume_task: (id: string) => Promise<DownloadTask>,
		retry_task: (id: string) => Promise<DownloadTask>,
		set_priority: (id: string, priority: number) => Promise<DownloadTask>,
		store_secret: (value: string) => Promise<string>,
		task_removed: { on: (listener: (event: TaskRemovedEvent) => void) => Promise<UnlistenFn> },
		task_upsert: { on: (listener: (event: TaskUpsertEvent) => void) => Promise<UnlistenFn> },
		update_settings: (settings: DownloaderSettings) => Promise<DownloaderSettings>,
		update_source: (id: string, source: DownloadSource) => Promise<DownloadTask>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }
