// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult } from 'taurpc'
export type Result<T, E> = {
	ok: T,
	err: E,
};
const ARGS_MAP = {"db":{"native_store_get":["namespace","key"],"native_store_remove":["namespace","key"],"native_store_set":["namespace","key","value"]}};

const RESULT_MAP = {"db":{"native_store_get":true,"native_store_remove":true,"native_store_set":true}};

export type Router = {
	db: {
		native_store_get: (namespace: string, key: string) => Promise<string | null>,
		native_store_remove: (namespace: string, key: string) => Promise<null>,
		native_store_set: (namespace: string, key: string, value: string) => Promise<null>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }
