// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult } from 'taurpc'
const ARGS_MAP = {"app":{"get_runtime_platform":[]}};

const RESULT_MAP = {"app":{"get_runtime_platform":false}};

export type Router = {
	app: {
		get_runtime_platform: () => Promise<string>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }
